# Generated by Django 5.1 on 2024-08-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'verbose_name': 'إذن صرف', 'verbose_name_plural': 'إذونات الصرف'},
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='description',
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='approved_by',
            field=models.CharField(default=1, max_length=100, verbose_name='المعتمد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payee',
            field=models.CharField(max_length=100, verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_number',
            field=models.CharField(max_length=20, verbose_name='رقم الإذن'),
        ),
    ]
