# Generated by Django 5.1 on 2024-08-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0002_alter_paymentvoucher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={},
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
