# Generated by Django 5.1 on 2024-08-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0004_alter_paymentvoucher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advance',
            options={'verbose_name': 'سلفة', 'verbose_name_plural': 'السلف'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'إيداع', 'verbose_name_plural': 'الإيداعات'},
        ),
        migrations.AlterModelOptions(
            name='depositdiscrepancy',
            options={'verbose_name': 'فرق الإيداع', 'verbose_name_plural': 'فروق الإيداعات'},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'verbose_name': 'إعانة', 'verbose_name_plural': 'الإعانات'},
        ),
        migrations.AlterModelOptions(
            name='outstandingitem',
            options={'verbose_name': 'عنصر معلق', 'verbose_name_plural': 'العناصر المعلقة'},
        ),
        migrations.AlterModelOptions(
            name='reconciliationmemo',
            options={'verbose_name': 'مذكرة تسوية', 'verbose_name_plural': 'مذكرات التسوية'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name': 'مسحوب', 'verbose_name_plural': 'المسحوبات'},
        ),
        migrations.AlterField(
            model_name='advance',
            name='advance_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم السلفة'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المعتمد'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='purpose',
            field=models.TextField(verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.CharField(max_length=255, verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الإيداع'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='depositdiscrepancy',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الفعلي'),
        ),
        migrations.AlterField(
            model_name='depositdiscrepancy',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_care.deposit', verbose_name='الإيداع'),
        ),
        migrations.AlterField(
            model_name='depositdiscrepancy',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='depositdiscrepancy',
            name='discrepancy_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الفرق'),
        ),
        migrations.AlterField(
            model_name='depositdiscrepancy',
            name='recorded_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المسجل'),
        ),
        migrations.AlterField(
            model_name='depositdiscrepancy',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='تم التسوية'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المعتمد'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الإعانة'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='purpose',
            field=models.TextField(verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='outstandingitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='outstandingitem',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='outstandingitem',
            name='item_number',
            field=models.CharField(max_length=50, verbose_name='رقم العنصر'),
        ),
        migrations.AlterField(
            model_name='outstandingitem',
            name='item_type',
            field=models.CharField(choices=[('Cheque', 'شيك'), ('Deposit', 'إيداع')], max_length=50, verbose_name='نوع العنصر'),
        ),
        migrations.AlterField(
            model_name='outstandingitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'معلق'), ('Cleared', 'تم تسويته')], max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='reconciliationmemo',
            name='account',
            field=models.CharField(max_length=255, verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='reconciliationmemo',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='reconciliationmemo',
            name='memo_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم المذكرة'),
        ),
        migrations.AlterField(
            model_name='reconciliationmemo',
            name='notes',
            field=models.TextField(verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='reconciliationmemo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account',
            field=models.CharField(max_length=255, verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم المسحوب'),
        ),
    ]
