# Generated by Django 5.1 on 2024-08-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0005_alter_advance_options_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجهة')),
            ],
        ),
        migrations.AddField(
            model_name='advance',
            name='guarantor',
            field=models.CharField(default=1, max_length=255, verbose_name='الضامن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='guarantor_id',
            field=models.CharField(default=1, max_length=255, verbose_name='الضامن - رقم الوطني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='recipient_id',
            field=models.CharField(default=1, max_length=255, verbose_name='المستفيد - رقم الوطني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='guarantor_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='social_care.entity', verbose_name='الجهة تابع لها - المستفيد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='recipient_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='social_care.entity', verbose_name='الجهة تابع لها - المستفيد'),
            preserve_default=False,
        ),
    ]
