# Generated by Django 5.1 on 2024-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0006_entity_advance_guarantor_advance_guarantor_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'الجهات التابعة', 'verbose_name_plural': 'الجهات التابعة'},
        ),
        migrations.RemoveField(
            model_name='reconciliationmemo',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='reconciliationmemo',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='additional_bank_entries',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إضافة مبالغ في كشف الحساب'),
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='beginning_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='رصيد دفتر بداية الشهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='checks_not_cleared',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='صكوك لم تظهر'),
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='deductions_not_recorded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='طرح لم تسجل في الدفتر'),
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='deposit_discrepancies',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='فروقات إيداع'),
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='deposits_during_month',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الإيداع خلال الشهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='ending_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='رصيد دفتر نهاية الشهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='reconciled_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الرصيد الدفتري بعد التسوية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='statement_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='رصيد كشف حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='unrecorded_revenues',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إيرادات لم تسجل في الدفتر'),
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='withdrawal_discrepancies',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='فروقات سحب'),
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='withdrawals_during_month',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='المسحوبات خلال الشهر'),
            preserve_default=False,
        ),
    ]
