# Generated by Django 5.1 on 2024-08-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0007_alter_entity_options_remove_reconciliationmemo_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationmemo',
            name='deductions_not_recorded',
        ),
        migrations.AddField(
            model_name='reconciliationmemo',
            name='checks_not_recorded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='صكوك لم تسجل في الدفتر'),
        ),
    ]
