# Generated by Django 5.1 on 2024-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0008_remove_reconciliationmemo_deductions_not_recorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='guarantor',
            field=models.CharField(max_length=255, unique=True, verbose_name='الضامن'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='guarantor_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='الضامن - رقم الوطني'),
        ),
    ]
