# Generated by Django 5.1 on 2024-08-12 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0009_alter_advance_guarantor_alter_advance_guarantor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='reconciliation_memo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='social_care.reconciliationmemo', verbose_name='مذكرة التسوية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='recipient_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='social_care.entity', verbose_name='الجهة تابع لها - المستفيد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='recipient_id',
            field=models.CharField(default=1, max_length=255, verbose_name='رقم الوطني للمستفيد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outstandingitem',
            name='reconciliation_memo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_items', to='social_care.reconciliationmemo', verbose_name='مذكرة التسوية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reconciliation_memo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='social_care.reconciliationmemo', verbose_name='مذكرة التسوية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advance',
            name='guarantor_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='social_care.entity', verbose_name='الجهة تابع لها - الضامن'),
        ),
    ]
