# Generated by Django 5.1 on 2024-08-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0010_deposit_reconciliation_memo_grant_recipient_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositdiscrepancy',
            name='deposit',
        ),
        migrations.AddField(
            model_name='depositdiscrepancy',
            name='reconciliation_memo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_discrepancy', to='social_care.reconciliationmemo', verbose_name='مذكرة التسوية'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reconciliation_memo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='social_care.reconciliationmemo', verbose_name='مذكرة التسوية'),
        ),
        migrations.AlterField(
            model_name='outstandingitem',
            name='reconciliation_memo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_items', to='social_care.reconciliationmemo', verbose_name='مذكرة التسوية'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reconciliation_memo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='social_care.reconciliationmemo', verbose_name='مذكرة التسوية'),
        ),
    ]
