# Generated by Django 5.1 on 2024-08-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_care', '0011_remove_depositdiscrepancy_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlistedBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الصك')),
                ('bond_date', models.DateField(verbose_name='تاريخ الصك')),
                ('bond_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قيمة الصك')),
                ('issuer', models.CharField(max_length=255, verbose_name='الجهة المصدرة')),
                ('reason_not_listed', models.TextField(blank=True, null=True, verbose_name='سبب عدم الظهور')),
                ('detected_on', models.DateField(blank=True, null=True, verbose_name='تاريخ اكتشاف الصك')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reconciliation_memo', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlisted_bond', to='social_care.reconciliationmemo', verbose_name='صك لم يظهر')),
            ],
            options={
                'verbose_name': 'صك لم يظهر',
                'verbose_name_plural': 'صكوك لم تظهر',
            },
        ),
        migrations.CreateModel(
            name='UnregisteredBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الصك')),
                ('bond_date', models.DateField(verbose_name='تاريخ الصك')),
                ('bond_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قيمة الصك')),
                ('issuer', models.CharField(max_length=255, verbose_name='الجهة المصدرة')),
                ('reason_not_registered', models.TextField(blank=True, null=True, verbose_name='سبب عدم التسجيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reconciliation_memo', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_bond', to='social_care.reconciliationmemo', verbose_name='صك غير مسجل')),
            ],
            options={
                'verbose_name': 'صك غير مسجل',
                'verbose_name_plural': 'صكوك غير مسجلة',
            },
        ),
    ]
